name: Remove old images

on:
  workflow_dispatch:
  schedule:
  - cron: '25 4 * * *'

jobs:
  remove-old-images:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all untagged container versions
        uses: actions/delete-package-versions@v5
        with:
          delete-only-untagged-versions: false
          min-versions-to-keep: 8
          package-name: 'dgg-stats.github.io'
          package-type: container
